version: "3.9"

# TODO: env перенести в git secrets

services:

    db_test:
        image: postgres:13.3
        container_name: database_test
        restart: always
        ports:
            - "5433:5432"
        # Пример виртуального окружения. (Должно совпадать с backend)
        environment:
            POSTGRES_DB: "postgres_test"
            POSTGRES_USER: "postgres_test"
            POSTGRES_PASSWORD: "postgres_test"

    db:
        image: postgres:13.3
        container_name: database
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - /var/lib/postgresql/data
        # Пример виртуального окружения. (Должно совпадать с backend)
        environment:
            POSTGRES_DB: "postgres"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"

    backend:
        build: './backend'
        container_name: backend
        command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"
        restart: always
        depends_on:
            - db_test
            - db
        ports:
            - 8000:8000

        #  Пример виртуального окружения. (Должно совпадать с db и db_test)
        #  Для боевого проекта рекомендуется переменные env сохранить в git secrets
        environment:
            - SECRET_KEY=SomeSuperSecretKey
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_NAME=postgres
            - DB_HOST=db
            - DB_PORT=5432
            - DB_USER_TEST=postgres_test
            - DB_PASSWORD_TEST=postgres_test
            - DB_NAME_TEST=postgres_test
            - DB_HOST_TEST=localhost
            - DB_PORT_TEST=5433
            - JWT_ALGORITHM=HS256
            - JWT_EXPIRE_MIN=10_000